project_name: multibrowser

builds:
  - id: linux
    main: ./main.go
    binary: multibrowser
    goos:
      - linux
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
    flags:
      - -tags=webkit2_41

  - id: windows
    main: ./main.go
    binary: multibrowser
    goos:
      - windows
    goarch:
      - amd64
    env:
      - CGO_ENABLED=1
      - CC=x86_64-w64-mingw32-gcc
      - CXX=x86_64-w64-mingw32-g++
    ldflags:
      - -H windowsgui

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md

release:
  github:
    owner: lguifcosta
    name: multibrowser

checksum:
  name_template: "checksums.txt"
