#!/bin/bash
set -e

APP=multibrowser

# Use the binary generated by GoReleaser
# GoReleaser by default puts binaries in dist/app_linux_amd64/multibrowser
# depending on your config. Let's check where GoReleaser will put it.

mkdir -p AppDir/usr/bin
cp dist/app_linux_amd64/multibrowser AppDir/usr/bin/multibrowser

mkdir -p AppDir/usr/share/applications
cat > AppDir/usr/share/applications/multibrowser.desktop <<EOL
[Desktop Entry]
Name=MultiBrowser
Exec=multibrowser
Icon=multibrowser
Type=Application
Categories=Utility;
Terminal=false
EOL

mkdir -p AppDir/usr/share/icons/hicolor/256x256/apps
cp build/appicon.png AppDir/usr/share/icons/hicolor/256x256/apps/multibrowser.png

wget -q https://github.com/linuxdeploy/linuxdeploy/releases/download/continuous/linuxdeploy-x86_64.AppImage
chmod +x linuxdeploy-x86_64.AppImage

export APPIMAGE_EXTRACT_AND_RUN=1
./linuxdeploy-x86_64.AppImage   --appdir AppDir   --output appimage

# Move to dist to be uploaded by release action
mv *.AppImage dist/
