// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {profile} from '../models';

export function CleanCache(arg1:string):Promise<number>;

export function CloneProfile(arg1:string,arg2:string):Promise<profile.Profile>;

export function CreateProfile(arg1:string):Promise<profile.Profile>;

export function DeleteProfile(arg1:string):Promise<void>;

export function ExportBackup(arg1:string,arg2:boolean,arg3:string):Promise<string>;

export function GetChromiumPath():Promise<string>;

export function ImportBackup(arg1:string,arg2:string,arg3:string):Promise<profile.Profile>;

export function IsProfileRunning(arg1:string):Promise<boolean>;

export function LaunchProfile(arg1:string):Promise<number>;

export function ListProfiles():Promise<Array<profile.Profile>>;

export function RenameProfile(arg1:string,arg2:string):Promise<void>;

export function SetChromiumPath(arg1:string):Promise<void>;

export function StopProfile(arg1:string):Promise<void>;
