// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function AssignProfileToGroup(arg1, arg2) {
  return window['go']['main']['App']['AssignProfileToGroup'](arg1, arg2);
}

export function CleanCache(arg1) {
  return window['go']['main']['App']['CleanCache'](arg1);
}

export function CloneProfile(arg1, arg2) {
  return window['go']['main']['App']['CloneProfile'](arg1, arg2);
}

export function CreateGroup(arg1) {
  return window['go']['main']['App']['CreateGroup'](arg1);
}

export function CreateProfile(arg1) {
  return window['go']['main']['App']['CreateProfile'](arg1);
}

export function DeleteGroup(arg1) {
  return window['go']['main']['App']['DeleteGroup'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function DetectBrowsers() {
  return window['go']['main']['App']['DetectBrowsers']();
}

export function ExportBackup(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportBackup'](arg1, arg2, arg3);
}

export function GetBrowserName() {
  return window['go']['main']['App']['GetBrowserName']();
}

export function GetBrowserPath() {
  return window['go']['main']['App']['GetBrowserPath']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetProfileFlags(arg1) {
  return window['go']['main']['App']['GetProfileFlags'](arg1);
}

export function GetProfileInfo(arg1) {
  return window['go']['main']['App']['GetProfileInfo'](arg1);
}

export function GetProfileTelemetry(arg1) {
  return window['go']['main']['App']['GetProfileTelemetry'](arg1);
}

export function HasBrowser() {
  return window['go']['main']['App']['HasBrowser']();
}

export function ImportBackup(arg1, arg2, arg3) {
  return window['go']['main']['App']['ImportBackup'](arg1, arg2, arg3);
}

export function IsProfileRunning(arg1) {
  return window['go']['main']['App']['IsProfileRunning'](arg1);
}

export function LaunchProfile(arg1) {
  return window['go']['main']['App']['LaunchProfile'](arg1);
}

export function ListGroups() {
  return window['go']['main']['App']['ListGroups']();
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']();
}

export function RenameGroup(arg1, arg2) {
  return window['go']['main']['App']['RenameGroup'](arg1, arg2);
}

export function RenameProfile(arg1, arg2) {
  return window['go']['main']['App']['RenameProfile'](arg1, arg2);
}

export function ReorderGroups(arg1) {
  return window['go']['main']['App']['ReorderGroups'](arg1);
}

export function SetBrowser(arg1, arg2) {
  return window['go']['main']['App']['SetBrowser'](arg1, arg2);
}

export function SetCustomBrowserPath(arg1) {
  return window['go']['main']['App']['SetCustomBrowserPath'](arg1);
}

export function StopProfile(arg1) {
  return window['go']['main']['App']['StopProfile'](arg1);
}

export function UpdateConfig(arg1) {
  return window['go']['main']['App']['UpdateConfig'](arg1);
}

export function UpdateProfileFlags(arg1, arg2) {
  return window['go']['main']['App']['UpdateProfileFlags'](arg1, arg2);
}
