// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CleanCache(arg1) {
  return window['go']['main']['App']['CleanCache'](arg1);
}

export function CloneProfile(arg1, arg2) {
  return window['go']['main']['App']['CloneProfile'](arg1, arg2);
}

export function CreateProfile(arg1) {
  return window['go']['main']['App']['CreateProfile'](arg1);
}

export function DeleteProfile(arg1) {
  return window['go']['main']['App']['DeleteProfile'](arg1);
}

export function ExportBackup(arg1, arg2, arg3) {
  return window['go']['main']['App']['ExportBackup'](arg1, arg2, arg3);
}

export function GetChromiumPath() {
  return window['go']['main']['App']['GetChromiumPath']();
}

export function ImportBackup(arg1, arg2, arg3) {
  return window['go']['main']['App']['ImportBackup'](arg1, arg2, arg3);
}

export function IsProfileRunning(arg1) {
  return window['go']['main']['App']['IsProfileRunning'](arg1);
}

export function LaunchProfile(arg1) {
  return window['go']['main']['App']['LaunchProfile'](arg1);
}

export function ListProfiles() {
  return window['go']['main']['App']['ListProfiles']();
}

export function RenameProfile(arg1, arg2) {
  return window['go']['main']['App']['RenameProfile'](arg1, arg2);
}

export function SetChromiumPath(arg1) {
  return window['go']['main']['App']['SetChromiumPath'](arg1);
}

export function StopProfile(arg1) {
  return window['go']['main']['App']['StopProfile'](arg1);
}
